// default package
// Generated Dec 18, 2015 5:55:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Countrylanguage generated by hbm2java
 */
public class Countrylanguage implements java.io.Serializable {

	private CountrylanguageId id;
	private Country country;
	private String isOfficial;
	private float percentage;

	public Countrylanguage() {
	}

	public Countrylanguage(CountrylanguageId id, Country country, String isOfficial, float percentage) {
		this.id = id;
		this.country = country;
		this.isOfficial = isOfficial;
		this.percentage = percentage;
	}

	public CountrylanguageId getId() {
		return this.id;
	}

	public void setId(CountrylanguageId id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getIsOfficial() {
		return this.isOfficial;
	}

	public void setIsOfficial(String isOfficial) {
		this.isOfficial = isOfficial;
	}

	public float getPercentage() {
		return this.percentage;
	}

	public void setPercentage(float percentage) {
		this.percentage = percentage;
	}

}
